### PR TITLE
Added a French translation

### PR DESCRIPTION
**Pull request by GRA0007**
French is not my first language so tell me if you spot any errors.

### CODE REVIEW

**Comment by Mrcomputer1** [comment]
> if you spot any errors.

Ummm. I don't know french so I can't :P

**Comment by GRA0007** [comment]
lol

**Comment by Mrcomputer1** [comment]
Now to put the translation on the website...

**Comment by Mrcomputer1** [comment]
Translation now on website :D

[Link to try it](https://mrcomputer1.tk/progressdraw.html?_#lang=fr)

**Pull request merged**
